### PR TITLE
Sensitive field option for credential fields

### PR DESCRIPTION
**Pull request by jdef**
Custom protobuf option for fields that MAY contain sensitive, secret information. Allows for introspection of CSI message data using specific protobuf options, which is a more robust approach than the current alternative (testing field names).

* partial fix for #206

### CODE REVIEW

**Comment by jdef** [comment]
rebased to master

**Comment by jdef** [comment]
Jie was wondering how I came up with the extension number. I basically just picked a large number that I thought would not collide with anything else in the spec. Well, apparently there's a registry of extension numbers for public projects. So if we want this PR to land, we'll probably need to register an extension number.

See https://github.com/protocolbuffers/protobuf/blob/master/docs/options.md

**Comment by jdef** [comment]
https://github.com/protocolbuffers/protobuf/pull/5319

**Comment by jdef** [comment]
Once we are assigned an official extension range I can bump this PR to use a number from that range.

**Comment by jdef** [comment]
rebased to master

**Comment by saad-ali** [comment]
protocolbuffers/protobuf#5319 has merged. We should be good to use 1059. PR needs rebase.

**Pull request closed without merging**
