### PR TITLE
GetCapacityResponse: promote maximum_volume_size

### PR DESCRIPTION
**Pull request by pohly**
[Kubernetes](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1472-storage-capacity-tracking/README.md) and several CSI drivers (for example, [PMEM-CSI](https://github.com/intel/pmem-csi/blob/8ed05e3a38eba355c1d57e00d38b3fd9c3559d70/pkg/pmem-csi-driver/controllerserver-node.go#L475-L486)) have been using that field for a while now
and no changes to the semantic are expected, therefore the alpha status can and
should be removed.

The minimum_volume_size field is not used by Kubernetes. The semantic is
probably stable, but further practical experience with it might be desirable
before promoting it.

### CODE REVIEW

**Comment by humblec** [comment]
may be its good to give some references in the PR description to its usage in kube or csi drivers as we are promoting this field.

**Comment by pohly** [comment]
I've added some links.

**Comment by humblec** [comment]
lgtm..

**Comment by jdef** [comment]
RIP travis.org
> Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

Please regenerate the Go bindings since you're changing a protobuf descriptor.

**Review by jdef — APPROVED** [review]

**Comment by pohly** [comment]
Can this be merged and included in a new release?

**Comment by pohly** [comment]
The fix for the Makefile is in https://github.com/container-storage-interface/spec/pull/500. I did not include the updated lib/go/csi/csi.pb.go there because that's already pending here, but it might be cleaner to merge that change via the other PR.

**Comment by saad-ali** [comment]
> RIP travis.org
> 
> > Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

Opened https://github.com/container-storage-interface/spec/issues/501

**Pull request merged**
