### PR TITLE
Add mkfs_options to VolumeCapability.MountVolume

### PR DESCRIPTION
**Pull request by nixpanic**
Make it possible to add options to `mkfs` for formatting a filesystem.
With additional options to create a filesystem on a volume, provisioners
can be instructed to enable/disable certain features that may not be
available on all nodes.

See-also: ceph/ceph-csi#374
Fixes: #402

### CODE REVIEW

**Comment by NicolasT** [comment]
While mount flags are something one may want to change over time for a particular volume, the options used to create this filesystem (`mkfs` flags) can't be changed over time (after initial formatting) across a volume's lifetime (some options may be reconfigurable, but then those are not strictly `mkfs` options).

As such, shouldn't this information be only made available to the `CreateVolume` call, instead of passing it to a bunch of RPC calls that have little to no use for it?

**Comment by ameade** [comment]
> While mount flags are something one may want to change over time for a particular volume, the options used to create this filesystem (`mkfs` flags) can't be changed over time (after initial formatting) across a volume's lifetime (some options may be reconfigurable, but then those are not strictly `mkfs` options).
> 
> As such, shouldn't this information be only made available to the `CreateVolume` call, instead of passing it to a bunch of RPC calls that have little to no use for it?

I think a lot of CSI drivers do the format on NodeStageVolume since that's when they have the volume mounted.

**Comment by pohly** [comment]
I agree that this is common, but can't such CSI drivers take such parameters through the CreateVolume call, store them in the volume context, and then use that during NodeStageVolume?

**Comment by nixpanic** [comment]
> I agree that this is common, but can't such CSI drivers take such parameters through the CreateVolume call, store them in the volume context, and then use that during NodeStageVolume?

Yes, this is a very good alternative.

**Pull request closed without merging**
