### PR TITLE
Revert "use go v1.18 and update dependencies"

### PR DESCRIPTION
**Pull request by humblec**
Additional Info#
  This reverts commit 150c9d9ed3cb0cb4b9ea90e0a95888e5894eb038 partially.
  It keep the go.mod module version to 1.18 but leave old versions of genproto.
  Dropping this dependency back to its prior level would help downstreams avoid pulling in a ton of extra deps till we figure out how to consume bits from genproto in a more isolated way 

Ref# https://github.com/container-storage-interface/spec/commit/150c9d9ed3cb0cb4b9ea90e0a95888e5894eb038#r87967287

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce an API-breaking change?**:

```release-note
none
```

### CODE REVIEW

**Comment by humblec** [comment]
Cc @liggit

**Comment by bertinatto** [comment]
/assign @saad-ali @jdef 
Who LGTM'd the previous PR.

**Comment by liggitt** [comment]
The go1.18 change was fine, the genproto bump was the issue

**Comment by bertinatto** [comment]
Also, note that `v1.5.2` is not the latest version of protobuf. The module has been renamed and migrated to https://github.com/protocolbuffers/protobuf-go.

**Review by jdef — APPROVED** [review]
LGTM

**Comment by jdef** [comment]
@saad-ali it seems this would be worth cherry-picking for 1.7

**Comment by saad-ali** [comment]
LGTM

Will merge and cherry pick to 1.7

**Comment by saad-ali** [comment]
Is there a related bug or issue where this was discussed? Curious who/where the related issues were caught?

**Review by saad-ali — APPROVED** [review]
LGTM

**Comment by humblec** [comment]
> Is there a related bug or issue where this was discussed? Curious who/where the related issues were caught?

The references I have here is the one in PR description (https://github.com/container-storage-interface/spec/commit/150c9d9ed3cb0cb4b9ea90e0a95888e5894eb038#r87967287)  from @liggitt

**Comment by liggitt** [comment]
See https://github.com/kubernetes/kubernetes/issues/113366

**Pull request merged**
