### PR TITLE
spec: NodeID to string

### PR DESCRIPTION
**Pull request by jdef**
This patch updates all references to NodeID so that it is now a
simple string value. Associated field names and error codes have been
updated accordingly.

### CODE REVIEW

**Comment by jdef** [comment]
#121

**Comment by jieyu** [comment]
@saad-ali @julian-hj @cpuguy83, can you guys take a look?

**Comment by akutz** [comment]
This LGTM. I'm currently updating GoCSI, so the sooner this gets merged the better. Thanks!

**Pull request merged**
