### PR TITLE
Revert "Promote GetVolume and VolumeCondition to GA"

### PR DESCRIPTION
**Pull request by xing-yang**
Reverts container-storage-interface/spec#517

There are still discussions regarding this feature.  We need more time to reach consensus.  I'm going to revert this PR so that it won't block the 1.7 release. We need to release 1.7 to unblock [Promote DelegateFSGroupToCSIDriver feature to GA](https://github.com/kubernetes/kubernetes/pull/113225) in K8s 1.26.
https://kubernetes.slack.com/archives/C8EJ01Z46/p1666708807369589

### CODE REVIEW

**Comment by xing-yang** [comment]
@jdef @saad-ali Please take a look.

**Comment by gnufied** [comment]
LGTM

**Comment by saad-ali** [comment]
LGTM

Will let @jdef approve and merge

**Review by jdef — APPROVED** [review]
LGTM

**Pull request merged**
