### PR TITLE
 Added Nomad to Container Orchestrators #421

### PR DESCRIPTION
**Pull request by mpron**
Added a bullet link for Nomad to the readme file linking to the information about CSI support. New feature so it may change as documentation pages are created.

### CODE REVIEW

**Comment by tgross** [comment]
Hi folks, I'm on the Nomad team and was prepping to make a PR myself when I saw this one. We would recommend https://nomadproject.io/docs/internals/plugins/csi/ as a better link.

**Comment by jieyu** [comment]
@mpron could you update link according to @tgross ?

**Comment by mpron** [comment]
Done.  Sorry I jumped the gun @tgross

**Comment by tgross** [comment]
> Sorry I jumped the gun @tgross

Not at all! Thanks!

**Comment by shantanugadgil** [comment]
can this be merged now?

**Comment by mpron** [comment]
@shantanugadgil yes.

**Comment by shantanugadgil** [comment]
Gak! Celebrated too soon. Will wait for this to be merged!

**Comment by shantanugadgil** [comment]
@tgross  @jieyu @jdef anything holding this back from merging? 😃

**Comment by saad-ali** [comment]
LGTM

**Comment by jieyu** [comment]
@mpron could you please sign the CLA https://github.com/container-storage-interface/spec/blob/master/CCLA.pdf and email to container-storage-interface-approvers@googlegroups.com ?

**Comment by mpron** [comment]
@tgross I leave this to you and your team to run this up the corporate ladder.  I'm definitely not the right person to sign that CLA.  I'll bow out of this thread now. :)

**Comment by jieyu** [comment]
@tgross @mpron let me know how you want us to make progress here. Unfortunately, the CLA is a legal boilerplate we'll have to do. I am happy to submit a PR for you guys (I already signed the CLA).

**Comment by tgross** [comment]
Hi @jieyu, sorry about the delay.

We're still in the process of getting the CLA through our legal team. If you have time to submit the PR for us that'd be great. HashiCorp are going to continue to extend our CSI support in Nomad. So I'm sure we'll have contributions going forward anyways and our internal efforts won't be wasted even if you do so. Thanks!

**Comment by jieyu** [comment]
@tgross ok, sounds good. We'll wait for you guys to sort out the CLA then.

**Comment by galeep** [comment]
@jieyu A signed CLA has been sent your way!

**Comment by jieyu** [comment]
Signed CLA received. Merging.

**Pull request merged**
