### PR TITLE
spec: protobuf declares syntax and package name

### PR DESCRIPTION
**Pull request by jdef**

### CODE REVIEW

**Comment by jdef** [comment]
@akutz PTAL

**Comment by akutz** [comment]
LGTM (https://gist.github.com/jdef/57c2759a9e57bc9353f4cd1aafcfd134)

**Comment by akutz** [comment]
@jdef / @jieyu / @saad-ali,

I just noticed that this PR comes from a branch on this repo. I strongly suggest you use a fork as others will be doing so. You should dog-food your process and not create PRs directly on the project's repo unless they are release or support branches.

**Comment by jdef** [comment]
Good feedback @akutz. I'll submit future PRs from a forked repo.

**Comment by akutz** [comment]
Hi @jdef,

Additionally, your commit message's body should not exceed 72 characters in order to be a valid Git message body. I like this [blog](http://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message) for info on Git commit messages.

**Comment by akutz** [comment]
Also, according to @jieyu all text should be properly cased and full, English sentences. The commit message's subject and body do not adhere to that. I concur that intent is what matters, but @jieyu seemed very serious about every place I did not adhere to this rule, so I thought I'd mention it here as well.

**Comment by jdef** [comment]
Your attention to detail is appreciated. Overlooked the git-commit rules in
my haste to unblock other PRs. Would be nice if GH provided a better commit
message editor.

**Comment by akutz** [comment]
Hi @jdef,

Perhaps more time reviewing the PR prior to a merge? I was surprised @jieyu missed it :) As far as Git commit message editors, I use Vim and it has built-in support for indicating when the Git message and body width limits are exceeded. Just set this in your profile and Git will use Vim to edit commits messages:

```bash
export EDITOR=vim
```

**Comment by akutz** [comment]
I also recommend, as I did to @jieyu the other day with his style-related PR, that PRs should have meaningful descriptions. Perhaps simply copy the commit message's body? A PR with an empty description is a bad look IMO.

**Comment by jieyu** [comment]
Sorry, I overlooked the commit body. Probably we should add a commit hook to check that.

**Comment by akutz** [comment]
Or just edit them in Vim and rely on it handling it for you. It's not difficult to check locally.

**Comment by jieyu** [comment]
I guess @jdef hit squash and merge button from github, thus having this issue.

**Comment by akutz** [comment]
Ugh. I don't trust that myself. How do you guys like it?

**Comment by jdef** [comment]
Not as precise as vim. Does the job in a pinch but, as you've observed,
makes it easy to break rules..

**Pull request merged**
