### PR TITLE
make use of latest checkout and setup actions in the workflow

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
Cc @jdef @saad-ali

**Comment by jdef** [comment]
Is this fixing anything, or just housekeeping?

**Comment by humblec** [comment]
> Is this fixing anything, or just housekeeping?
https://github.com/container-storage-interface/spec/pull/524 trying to update the dependencies, so making sure latest go has been used in the actions too

**Comment by humblec** [comment]
@jdef ptal. thanks in advance!

**Review by jdef — APPROVED** [review]
LGTM, thanks

**Comment by humblec** [comment]
> LGTM, thanks

@jdef yw!  looks like we can merge this in..

**Pull request merged**
