### PR TITLE
spec: created_at is a Timestamp.

### LINKED ISSUE #330: spec: Snapshot.created_at should use well-known Timestamp protobuf
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto

This would be a breaking change after 1.0, so if this change doesn't land before then maybe we could eventually use a `oneof` to wrap the existing int-based timestamp and a new field that uses `Timestamp`.

Ideally we'd resolve this prior to 1.0

### PR DESCRIPTION
**Pull request by jdef**
Fixes #330

### CODE REVIEW

**Comment by saad-ali** [comment]
CC @xing-yang @jingxu97 for FYI

**Comment by jdef** [comment]
I'm happy to make that change later tonight or tomorrow morning... if
people want it

**Comment by saad-ali** [comment]
> I'm happy to make that change later tonight or tomorrow morning... if people want it

I'm fine with it too. Go for it. I'll wait for it.

**Comment by xing-yang** [comment]
Thanks @jdef!  Yes, Jing and I are fine with the change.  Renaming it to creation_time sounds good.

**Comment by jdef** [comment]
@julian-hj I've renamed the field - PTAL

**Comment by saad-ali** [comment]
LGTM

**Pull request merged**
